# Generated by Django 4.2.1 on 2026-06-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-image.avif', upload_to='profile_images'),
        ),
    ]
